{
    "name": "ADEC SOL HR Performance Evaluator",
    "version": "18.0.2.0.0",
    "category": "Human Resources",
    "author": "ADEC SOL",
    # 'website': 'https://www.adecsol.com',
    "license": "LGPL-3",
    "images": ["static/description/icon.png"],
    "summary": "Quản lý việc đánh giá hiệu suất làm việc của nhân viên bằng cách sử dụng các chỉ số KPI.",
    "depends": [
        "hr",
        "base",
        "mail",
        "contacts",
        "payroll",
        "hr_attendance",
        "hr_holidays",
        "project_task_done_date",
    ],
    "description": """

Mô-đun này được thiết kế để tối ưu hóa quy trình đánh giá và báo cáo hiệu suất, cung cấp cho các nhóm nhân sự những công cụ mạnh mẽ để quản lý và theo dõi hiệu suất của nhân viên.

    """,
    "data": [
        # ============================== SECURITY =============================
        "security/security.xml",
        "security/ir.model.access.csv",
        # ============================== DATA =============================
        "data/kpi_sequence.xml",
        "data/ir_config_parameter_data.xml",
        "data/hr_pillar_seed.xml",
        "demo/kpi_unit_data.xml",
        "data/hr_kpi_scoring_profile_data.xml",
        "data/hr_kpi_scoring_formula_data.xml",
        "data/hr_kpi_data_source_data.xml",
        # "demo/hr_kpi_it_3p_2026_04_seed(use_for_staging).xml",
        # commment hr_kpi_it_3p_2026_04_seed.xml để tránh bị trùng dữ liệu có sẵn của adecsol
        "data/hr_kpi_it_3p_2026_04_seed.xml",
        "data/hr_kpi_ktoan_3p_2026_04_seed.xml",
        "data/hr_kpi_auto_3p_2026_04_seed.xml",
        "data/hr_kpi_pkt_ltd_3p_2026_04_seed.xml",
        "data/hr_kpi_ptk_ltd_3p_2026_04_seed.xml",
        "data/hr_kpi_manager_pkt_ltd_3p_seed.xml",
        # "data/hr_kpi_dashboard_widget_seed.xml",
        "data/kpi_period_seed.xml",
        "data/ir_cron_data.xml",
        # ============================== VIEWS =============================
        "views/res_config_settings_views.xml",
        "views/hr_kpi_period_views.xml",
        "views/hr_evaluation_master_views.xml",
        "views/kpi_unit_views.xml",
        "views/hr_kpi_data_source_views.xml",
        "views/hr_kpi_scoring_profile_views.xml",
        "views/hr_kpi_scoring_formula_views.xml",
        "views/hr_kpi_dashboard_widget_views.xml",
        "views/hr_kpi_scoring_formula_test_wizard_views.xml",
        "views/kpi_generate_wizard_views.xml",
        "views/hr_department_kpi_generate_wizard_views.xml",
        "views/performance_evaluation_approve_wizard_views.xml",
        "views/performance_evaluation_approve_all_wizard_views.xml",
        "views/kpi_view.xml",
        "views/hr_department_kpi_views.xml",
        "views/performance_evaluation.xml",
        "views/hr_department_evaluation_views.xml",
        "views/hr_evaluation_3p_summary_views.xml",
        "views/hr_score.xml",
        "views/hr_department.xml",
        "views/kpi_tree_dashboard_views.xml",
        "views/kpi_menu_views.xml",
        "demo/hr_payroll_3p_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "custom_adecsol_hr_performance_evaluator/static/src/scss/performance_badges.scss",
            "custom_adecsol_hr_performance_evaluator/static/src/scss/performance_evaluation.scss",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_dashboard/kpi_dashboard.scss",
            "custom_adecsol_hr_performance_evaluator/static/src/components/dept_kpi_dashboard/dept_kpi_dashboard.scss",
            "custom_adecsol_hr_performance_evaluator/static/src/utils/kpi_helpers.js",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_dashboard/kpi_dashboard_page.js",
            "custom_adecsol_hr_performance_evaluator/static/src/js/kpi_child_matrix_utils.js",
            "custom_adecsol_hr_performance_evaluator/static/src/js/kpi_child_matrix_fields.js",
            "custom_adecsol_hr_performance_evaluator/static/src/js/kpi_one2many.js",
            "custom_adecsol_hr_performance_evaluator/static/src/js/evaluation_one2many.js",
            "custom_adecsol_hr_performance_evaluator/static/src/js/priority_with_onchange.js",
            "custom_adecsol_hr_performance_evaluator/static/src/js/kpi_description_custom_widget.js",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_template_tree/kpi_template_tree_one2many.js",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_template_tree/kpi_template_tree_one2many.xml",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_dashboard/kpi_dashboard_template.xml",
            "custom_adecsol_hr_performance_evaluator/static/src/components/dept_kpi_dashboard/dept_kpi_dashboard.js",
            "custom_adecsol_hr_performance_evaluator/static/src/components/dept_kpi_dashboard/dept_kpi_dashboard_template.xml",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_step_table_editor/kpi_step_table_editor.js",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_step_table_editor/kpi_step_table_editor.xml",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_tree_dashboard/kpi_tree_dashboard.scss",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_tree_dashboard/kpi_tree_dashboard.js",
            "custom_adecsol_hr_performance_evaluator/static/src/components/kpi_tree_dashboard/kpi_tree_dashboard.xml",
        ],
        "web.assets_tests": [
            "custom_adecsol_hr_performance_evaluator/static/tests/tours/**/*",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
